ENH: UI: Consistency: Also support --input-files FILE [...] ;
This is useful with shell globbing.

diff --git a/bin/aggregateField b/bin/aggregateField
--- a/bin/aggregateField
+++ b/bin/aggregateField
@@ -1,13 +1,15 @@
 #!/bin/bash
 shopt -qs extglob
 
+: ${AGGREGATEFIELD_INPUTFILES_END=;}
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '--avg|--count|--join SEP|--max|--min|--sum|--unique-counts|--total-and-unique-counts [--has-header] -g|--group-by [-]N|HEADER-NAME [--result-first] [--sort-by [+-]group|[+-]result] [-F|--field-separator FIELD-SEPARATOR] [-s|--output-separator OUTPUT-SEPARATOR] [-]N|HEADER-NAME ...'
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-i|--input FILESPEC [-i ...] ... [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... -i|--input FILE [-i ...]|--input-files FILE [...] ${AGGREGATEFIELD_INPUTFILES_END} [-?|-h|--help]"
 }
 printUsage()
 {
@@ -44,19 +46,24 @@ HELPDESCRIPTION
 			it for calculation.
     --group-by|-g [-]N|HEADER-NAME
 			Aggregate numbers separately for each unique value in
-			(single) field N / with HEADER-NAME. Report the result for
-			each group as GROUP OFS RESULT1 [OFS RESULT2 ...].
+			(single) field N / with HEADER-NAME. Report the result
+			for each group as GROUP OFS RESULT1 [OFS RESULT2 ...].
     --result-first	Report as RESULT1 [OFS RESULT2 ...] OFS GROUP.
     --sort-by [+-]group|[+-]result
 			Sort the output by group or result (left to right),
 			ascending (+) or descending (-).
+    --input|-i FILE 	Read from FILE(s) instead of standard input.
+    --input-files FILE [...] ${AGGREGATEFIELD_INPUTFILES_END}
+			Read from the following FILE(s) i.e. all following
+			arguments until an argument consisting of '${AGGREGATEFIELD_INPUTFILES_END}'
+			is encountered instead of standard input.
 EXIT STATUS:
     99	If no numbers were encountered.
 HELPTEXT
 }
 
 typeset -a fsArgs
-typeset -a awkArgs=()
+typeset -a inputFilespecs=()
 outputSeparator=
 hasHeader=
 groupBy=
@@ -84,7 +91,23 @@ do
 			esac
 			shift
 			;;
-	--input|-i)		shift; awkArgs+=("$1"); shift;;
+	--input|-i)	shift; inputFilespecs+=("${1:?}"); shift;;
+	--input-files)	shift
+			while [ $# -gt 0 -a "$1" != "$AGGREGATEFIELD_INPUTFILES_END" ]
+			do
+			    inputFilespecs+=("$1")
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --input-files must be concluded with '${AGGREGATEFIELD_INPUTFILES_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			if [ ${#inputFilespecs[@]} -eq 0 ]; then
+			    echo 'ERROR: --input-files must be followed by at least one FILE.'; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			;;
 	--field-separator|-F)	shift; fsArgs=(-F "$1"); shift;;
 	--output-separator|-s)
 			shift; outputSeparator="${1?}"; shift;;
@@ -343,4 +366,4 @@ END {
 	}
     }
 }
-' "${awkArgs[@]}"
+' "${inputFilespecs[@]}"
diff --git a/bin/countFieldToPercentage b/bin/countFieldToPercentage
--- a/bin/countFieldToPercentage
+++ b/bin/countFieldToPercentage
@@ -1,6 +1,8 @@
 #!/bin/bash
 shopt -qs extglob
 
+: ${COUNTFIELDTOPERCENTAGE_INPUTFILES_END=;}
+
 printUsage()
 {
     cat <<HELPTEXT
@@ -10,18 +12,34 @@ that field. Exits with 99 if no rows were encountered.
 HELPTEXT
     echo
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[--has-header] [-F|--field-separator FS] [-]N|HEADER-NAME'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-i|--input FILESPEC [...] [-]N|HEADER-NAME [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... -i|--input FILE [-i ...]|--input-files FILE [...] ${COUNTFIELDTOPERCENTAGE_INPUTFILES_END} [-]N|HEADER-NAME [-?|-h|--help]"
 }
 
 typeset -a fsArgs
-typeset -a awkArgs=()
+typeset -a inputFilespecs=()
 hasHeader=
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 	--has-header)	shift; hasHeader=t;;
-	--input|-i)		shift; awkArgs+=("$1"); shift;;
+	--input|-i)	shift; inputFilespecs+=("${1:?}"); shift;;
+	--input-files)	shift
+			while [ $# -gt 0 -a "$1" != "$COUNTFIELDTOPERCENTAGE_INPUTFILES_END" ]
+			do
+			    inputFilespecs+=("$1")
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --input-files must be concluded with '${COUNTFIELDTOPERCENTAGE_INPUTFILES_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			if [ ${#inputFilespecs[@]} -eq 0 ]; then
+			    echo 'ERROR: --input-files must be followed by at least one FILE.'; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			;;
 	--field-separator|-F)	shift; fsArgs=(-F "$1"); shift;;
 	--)		shift; break;;
 	-+([0-9]))	break;;
@@ -108,4 +126,4 @@ END {
 	}
     }
 }
-' "${awkArgs[@]}"
+' "${inputFilespecs[@]}"
diff --git a/bin/removeIdenticalField b/bin/removeIdenticalField
--- a/bin/removeIdenticalField
+++ b/bin/removeIdenticalField
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+: ${REMOVEIDENTICALFIELD_INPUTFILES_END=;}
+
 printUsage()
 {
     cat <<HELPTEXT
@@ -8,11 +10,11 @@ values are identical. Exits with 99 if no rows were encountered.
 HELPTEXT
     echo
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[--has-header] [--keep-single] [-F|--field-separator FS] N|HEADER-NAME'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-i|--input FILESPEC [...] N|HEADER-NAME [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... -i|--input FILE [-i ...]|--input-files FILE [...] ${REMOVEIDENTICALFIELD_INPUTFILES_END} N|HEADER-NAME [-?|-h|--help]"
 }
 
 typeset -a fsArgs
-typeset -a awkArgs=()
+typeset -a inputFilespecs=()
 hasHeader=
 isKeepSingle=
 while [ $# -ne 0 ]
@@ -21,7 +23,23 @@ do
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 	--has-header)	shift; hasHeader=t;;
 	--keep-single)	shift; isKeepSingle=t;;
-	--input|-i)		shift; awkArgs+=("$1"); shift;;
+	--input|-i)	shift; inputFilespecs+=("${1:?}"); shift;;
+	--input-files)	shift
+			while [ $# -gt 0 -a "$1" != "$REMOVEIDENTICALFIELD_INPUTFILES_END" ]
+			do
+			    inputFilespecs+=("$1")
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --input-files must be concluded with '${REMOVEIDENTICALFIELD_INPUTFILES_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			if [ ${#inputFilespecs[@]} -eq 0 ]; then
+			    echo 'ERROR: --input-files must be followed by at least one FILE.'; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			;;
 	--field-separator|-F)	shift; fsArgs=(-F "$1"); shift;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
@@ -146,4 +164,4 @@ END {
 	printReadLines(0)
     }
 }
-' "${awkArgs[@]}"
+' "${inputFilespecs[@]}"
diff --git a/bin/truncateLongTail b/bin/truncateLongTail
--- a/bin/truncateLongTail
+++ b/bin/truncateLongTail
@@ -2,13 +2,14 @@
 shopt -qs extglob
 
 : ${TRUNCATELONGTAIL_INCLUDE_SEPARATOR:=[...]}
+: ${TRUNCATELONGTAIL_INPUTFILES_END=;}
 
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[--has-header] [-F|--field-separator FS] [-m|--include PATTERN [-m ...]] [-]N|HEADER-NAME'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-i|--input FILESPEC [...] [-]N|HEADER-NAME [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... -i|--input FILE [-i ...]|--input-files FILE [...] ${TRUNCATELONGTAIL_INPUTFILES_END} [-]N|HEADER-NAME [-?|-h|--help]"
 }
 printUsage()
 {
@@ -35,19 +36,40 @@ HELPDESCRIPTION
 			tail. ${TRUNCATELONGTAIL_INCLUDE_SEPARATOR:+A }${TRUNCATELONGTAIL_INCLUDE_SEPARATOR:-Nothing} is placed before it.
 			PATTERN is an AWK-style unanchored extended regular
 			expression.
+    --input|-i FILE 	Read from FILE(s) instead of standard input.
+    --input-files FILE [...] ${TRUNCATELONGTAIL_INPUTFILES_END}
+			Read from the following FILE(s) i.e. all following
+			arguments until an argument consisting of '${TRUNCATELONGTAIL_INPUTFILES_END}' is
+			encountered instead of standard input.
 HELPTEXT
 }
 
 includePattern=
 typeset -a fsArgs
-typeset -a awkArgs=()
+typeset -a inputFilespecs=()
 hasHeader=
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--has-header)	shift; hasHeader=t;;
-	--input|-i)	shift; awkArgs+=("$1"); shift;;
+	--input|-i)	shift; inputFilespecs+=("${1:?}"); shift;;
+	--input-files)	shift
+			while [ $# -gt 0 -a "$1" != "$TRUNCATELONGTAIL_INPUTFILES_END" ]
+			do
+			    inputFilespecs+=("$1")
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --input-files must be concluded with '${TRUNCATELONGTAIL_INPUTFILES_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			if [ ${#inputFilespecs[@]} -eq 0 ]; then
+			    echo 'ERROR: --input-files must be followed by at least one FILE.'; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			;;
 	--field-separator|-F)
 			shift; fsArgs=(-F "$1"); shift;;
 	--include|-m)	shift; includePattern+="${includePattern:+|}${1:?}"; shift;;
@@ -132,4 +154,4 @@ NR == 2 && hasHeader {
     }
 }
 
-' "${awkArgs[@]}"
+' "${inputFilespecs[@]}"
