distribution-over-the-{day,month,year}: Robustness: Add check for non-equal year/month/day/hour/minute field numbers
With the defaulting in place, accidental misconfiguration is not easy to detect.

diff --git a/bin/distribution-over-the-day b/bin/distribution-over-the-day
--- a/bin/distribution-over-the-day
+++ b/bin/distribution-over-the-day
@@ -138,6 +138,10 @@ do
 	*)		sparkArgs+=("$1"); shift;;
     esac
 done
+if [ $hourFieldNr -eq $minuteFieldNr ]; then
+    echo >&2 'ERROR: Minute field cannot be equal to hour field.'
+    exit 2
+fi
 
 IFS=$'\n'
 tally()
diff --git a/bin/distribution-over-the-month b/bin/distribution-over-the-month
--- a/bin/distribution-over-the-month
+++ b/bin/distribution-over-the-month
@@ -131,6 +131,10 @@ do
 	*)		sparkArgs+=("$1"); shift;;
     esac
 done
+if [ $dayFieldNr -eq $hourFieldNr ]; then
+    echo >&2 'ERROR: Hour field cannot be equal to day field.'
+    exit 2
+fi
 
 IFS=$'\n'
 tally()
diff --git a/bin/distribution-over-the-year b/bin/distribution-over-the-year
--- a/bin/distribution-over-the-year
+++ b/bin/distribution-over-the-year
@@ -130,6 +130,16 @@ do
 	*)		sparkArgs+=("$1"); shift;;
     esac
 done
+if [ $yearFieldNr -eq $monthFieldNr ]; then
+    echo >&2 'ERROR: Month field cannot be equal to year field.'
+    exit 2
+elif [ $monthFieldNr -eq $dayFieldNr ]; then
+    echo >&2 'ERROR: Day field cannot be equal to month field.'
+    exit 2
+elif [ $yearFieldNr -eq $dayFieldNr ]; then
+    echo >&2 'ERROR: Day field cannot be equal to year field.'
+    exit 2
+fi
 
 IFS=$'\n'
 tally()
