ENH: Robustness: Support --color instead of just checking for terminal output
distribution-autolinear does that as well; the color flag is important when executing in a loop with a pager around it.

diff --git a/bin/distribution-over-autorange b/bin/distribution-over-autorange
--- a/bin/distribution-over-autorange
+++ b/bin/distribution-over-autorange
@@ -12,7 +12,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf "Usage: echo -e '2021-12-31 11:01\\\\n2022-01-11 12:00\\\\n...' | %q %s\\n" "$(basename "$1")" '[--no-footer|--final-footer-only|footer-only-on-change|--footer-every N] [--graph-legend TEXT] [--footer-legend TEXT] [--force-legends] [--bucket-legend] [-F|--field-separator FS] [--slots-per-day N] [--slots-per-hour N] [--count-field C [--default-count C|""]] [-S|--no-splitting|--split-graph-field N [--split-graph-field ...]] [--as colorbox-calendar|green-[large-]calendar|...] [--over day|month|year|year-weekly|--weekly] [SPARK-ARGS ...] [-?|-h|--help]'
+    printf "Usage: echo -e '2021-12-31 11:01\\\\n2022-01-11 12:00\\\\n...' | %q %s\\n" "$(basename "$1")" '[--color=(always|auto|never)|--no-color] [--no-footer|--final-footer-only|footer-only-on-change|--footer-every N] [--graph-legend TEXT] [--footer-legend TEXT] [--force-legends] [--bucket-legend] [-F|--field-separator FS] [--slots-per-day N] [--slots-per-hour N] [--count-field C [--default-count C|""]] [-S|--no-splitting|--split-graph-field N [--split-graph-field ...]] [--as colorbox-calendar|green-[large-]calendar|...] [--over day|month|year|year-weekly|--weekly] [SPARK-ARGS ...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -75,6 +75,7 @@ EXIT STATUS:
 HELPTEXT
 }
 
+isColor=; [ -t 1 ] && isColor=t
 isSplitting=t
 isForceLegends=
 forceRange=
@@ -95,6 +96,22 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--no-color|--color=never)
+			isColor=; shift;;
+	--color=always)	isColor=t; shift;;
+	--color=auto)	shift;;
+	--color)	case "$2" in
+			    always) isColor=t;;
+			    never)  isColor=;;
+			    auto)   ;;
+			    *)	    echo >&2 "ERROR: Invalid --color arg: $2"
+				    echo >&2
+				    printUsage "$0" >&2
+				    exit 2
+				    ;;
+			esac
+			shift; shift
+			;;
 
 	--weekly)	distributionOverTheYearArgs+=("$1"); shift; isWeekly=t;;
 	--slots-per-day)
@@ -145,7 +162,7 @@ hasHours()
 typeset -a dayDistributionDefaultRenderArgs=()
 typeset -a monthDistributionDefaultRenderArgs=()
 typeset -a yearDistributionDefaultRenderArgs=()
-if [ -t 1 ]; then
+if [ "$isColor" ]; then
     dayDistributionDefaultRenderArgs=(--as green-calendar)
     monthDistributionDefaultRenderArgs=(--as green-calendar)
     yearDistributionDefaultRenderArgs=(--as green-calendar)
